-- Seed data index. The prompts themselves live in one upsert file per skill:
--   psql "$DATABASE_URL" -f seed-writing-prompts.sql
--   psql "$DATABASE_URL" -f seed-speaking-prompts.sql
--
-- Both are idempotent: fixed UUIDs, and re-running updates the row with that id in place.
-- Run them in the Neon SQL Editor (or psql) after `dotnet ef database update`.
--
-- ponytail: plain SQL instead of EF HasData, so it can be pasted straight into the Neon
-- console. Move to HasData if seeding ever needs to happen automatically on every fresh
-- database (CI, new dev machines).
