using System.Net;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using IELTS.AI.Evaluator.Data.Models;
using IELTS.AI.Evaluator.Functions.DTOs;
using IELTS.AI.Evaluator.Functions.Exceptions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IELTS.AI.Evaluator.Functions.Services;

/// <summary>One answer's recording as the browser captured it: Answer is the 1-based candidate answer
/// number, Seconds the recording's length as the browser measured it, Data the audio as base64.</summary>
public record SpeakingAudioClip(int Answer, string MimeType, decimal Seconds, string Data);
public record SpeakingEvaluateRequest(Guid SpeakingPromptId, string Part, List<SpeakingTurn> Turns,
    PronunciationResult? Pronunciation = null, // Band on input is ignored — the service always recomputes it.
    List<SpeakingAudioClip>? Audio = null,
    Guid? ClientSessionId = null); // generated by the browser when the session starts; see EvaluateAsync
public record SpeakingSessionDto(Guid SpeakingSessionId, decimal OverallBand, SpeakingFeedback Feedback);
public record SpeakingSessionHistoryItemDto(Guid SpeakingSessionId, string Part, string Topic, decimal OverallBand, DateTime CreatedAt, Guid SpeakingPromptId);
/// <summary>A playable recording: the answer it belongs to and a link that expires.</summary>
public record SpeakingAudioLink(int Answer, string Url);
public record SpeakingSessionDetailDto(Guid SpeakingSessionId, string Part, string Topic, string QuestionText,
    List<SpeakingTurn> Turns, decimal OverallBand, SpeakingFeedback Feedback, PronunciationResult? Pronunciation, DateTime CreatedAt,
    List<SpeakingAudioLink>? Audio = null);
/// <summary>What the practice page polls while an evaluation runs. Error is set only when Status is
/// "failed", and is fit to show the candidate.</summary>
public record SpeakingEvaluationStatusDto(string Status, DateTime StartedAt, string? Error);

/// <summary>The values of SpeakingEvaluation.Status.</summary>
public static class SpeakingEvaluationStatus
{
    public const string Processing = "processing";
    public const string Completed = "completed";
    public const string Failed = "failed";
}

public interface ISpeakingService
{
    /// <summary>Same token contract as IWritingService.EvaluateAsync: it aborts before Gemini is
    /// paid, never after.</summary>
    Task<SpeakingSessionDto> EvaluateAsync(Guid userId, string role, SpeakingEvaluateRequest request,
        CancellationToken ct = default);
    Task<SpeakingEvaluationStatusDto> GetEvaluationStatusAsync(Guid userId, Guid id);
    Task<List<SpeakingSessionHistoryItemDto>> GetHistoryAsync(Guid userId);
    Task<SpeakingSessionDetailDto> GetDetailAsync(Guid userId, Guid id);
}

public class SpeakingService : ISpeakingService
{
    private const int MaxTranscriptLength = 20_000;
    private const int MaxConversationLength = 30_000;
    // A Part 2 long turn is two minutes; anything past fifteen is not a real answer.
    private const decimal MaxTurnSeconds = 900;
    // Below this, a rate is one short answer's noise — "yes I do" in half a second reads as 360 wpm.
    private const decimal MinSecondsForSpeechRate = 10;
    private static readonly Regex PauseMarker = new(@"\[pause [^\]]*\]", RegexOptions.Compiled);
    private static readonly JsonSerializerOptions CamelCase = new(JsonSerializerDefaults.Web);

    /// <summary>Stamped on every new session; see SpeakingSession.FeedbackVersion.</summary>
    internal const int CurrentFeedbackVersion = 3;

    // Past this an attempt still marked processing has died without writing "failed" (the host was
    // recycled mid-call): scoring is capped at 150s plus a quick retry, far inside it.
    private static readonly TimeSpan StaleAfter = TimeSpan.FromMinutes(5);

    // Five minutes of recording per session, as the practice page caps it, plus slack for the clock
    // running a moment past the cap before the recorder stops.
    private const decimal MaxAudioSeconds = 310;
    // Five minutes at the browser's 32 kbps is about 1.2 MB; Safari's AAC may not honour that bitrate.
    private const int MaxAudioBytes = 3_000_000;
    // What the practice page's recorder produces, by base MIME type, and how Gemini names it.
    // Safari's audio/mp4 is MPEG-4 audio, which Gemini lists as audio/m4a.
    private static readonly Dictionary<string, (string GeminiType, string Extension)> AudioTypes = new()
    {
        ["audio/webm"] = ("audio/webm", "webm"),
        ["audio/ogg"] = ("audio/ogg", "ogg"),
        ["audio/mp4"] = ("audio/m4a", "m4a"),
    };

    /// <summary>A recording that passed validation, decoded.</summary>
    private sealed record DecodedClip(int Answer, string BrowserType, string GeminiType, string Extension, byte[] Data);

    /// <summary>What AudioClips stores per recording.</summary>
    private sealed record StoredAudioClip(int Answer, string BlobName);

    // Long enough to listen through a session's feedback; short enough that a copied link dies on its own.
    private static readonly TimeSpan AudioLinkLifetime = TimeSpan.FromMinutes(30);

    private readonly IGeminiStructuredClient _gemini;
    private readonly EvaluatorDbContext _db;
    private readonly IConfiguration _config;
    private readonly IAudioStore _audio;

    public SpeakingService(IGeminiStructuredClient gemini, EvaluatorDbContext db, IConfiguration config, IAudioStore audio)
    {
        _gemini = gemini;
        _db = db;
        _config = config;
        _audio = audio;
    }

    public async Task<SpeakingSessionDto> EvaluateAsync(Guid userId, string role, SpeakingEvaluateRequest request,
        CancellationToken ct = default)
    {
        if (request.SpeakingPromptId == Guid.Empty || string.IsNullOrWhiteSpace(request.Part) || request.Turns is not { Count: > 0 })
            throw new ValidationException("Speaking prompt, part, and turns are required.");

        var candidateTurns = request.Turns.Where(t => t.Role.Equals("candidate", StringComparison.OrdinalIgnoreCase)).ToList();
        if (candidateTurns.Count == 0)
            throw new ValidationException("At least one candidate turn is required.");

        var transcriptLength = candidateTurns.Sum(t => t.Text?.Length ?? 0);
        if (transcriptLength > MaxTranscriptLength)
            throw new ValidationException("Transcript exceeds the maximum length of 20,000 characters.");

        // Client-measured, so bounded here: it feeds the speech rate the scorer is shown.
        if (request.Turns.Any(t => t.DurationSeconds is < 0 or > MaxTurnSeconds))
            throw new ValidationException("Invalid turn duration.");

        // All turns (including examiner) are client-controlled and get rendered verbatim into the paid
        // Gemini call by BuildUserParts, so the candidate-only cap above isn't enough on its own.
        ValidateConversationCap(request.Turns);

        // Checked with everything else before any money is spent: format, size, length, and that each
        // recording belongs to an answer that exists.
        var clips = DecodeAudio(request.Audio, request.Turns.Count(t => !IsExaminer(t)));

        // A retried submission — a refresh, a browser that gave up waiting — carries the id its first
        // attempt used. Once that one is saved, hand it back instead of paying Gemini a second time.
        // Checked before the quota: the retry must not be refused for the slot its first attempt used.
        var sessionId = request.ClientSessionId is { } requested && requested != Guid.Empty ? requested : Guid.NewGuid();
        if (await _db.SpeakingSessions.AsNoTracking().FirstOrDefaultAsync(s => s.SpeakingSessionId == sessionId, ct) is { } saved)
        {
            if (saved.UserId != userId)
                throw new ValidationException("Invalid session id.");
            return new SpeakingSessionDto(saved.SpeakingSessionId, saved.OverallBand,
                JsonSerializer.Deserialize<SpeakingFeedback>(saved.Feedback, CamelCase)!);
        }

        // Not saved yet, but maybe still being scored: then the caller keeps polling rather than paying
        // twice. A failed or stale attempt is simply run again.
        // ponytail: two first attempts arriving at the same moment both pass this, and the second
        // insert below fails on the primary key; the page sends one, so only a client bug repeats it.
        var evaluation = await _db.SpeakingEvaluations.FirstOrDefaultAsync(e => e.SpeakingEvaluationId == sessionId, ct);
        if (evaluation is not null && evaluation.UserId != userId)
            throw new ValidationException("Invalid session id.");
        if (evaluation is not null && IsRunning(evaluation))
            throw new EvaluationInProgressException("This session is already being scored.");

        var prompt = await _db.SpeakingPrompts.FirstOrDefaultAsync(p => p.SpeakingPromptId == request.SpeakingPromptId, ct)
            ?? throw new NotFoundException("Speaking prompt not found.");

        var isUnlimitedPlan = role.Equals("Premium", StringComparison.OrdinalIgnoreCase)
            || role.Equals("Admin", StringComparison.OrdinalIgnoreCase);
        if (!isUnlimitedPlan)
        {
            var dailyLimit = int.TryParse(_config["DailySpeakingQuota"], out var configuredLimit) ? configuredLimit : 10;
            var todayUtc = DateTime.UtcNow.Date;
            // ponytail: COUNT-then-proceed is racy under concurrency; acceptable at this scale — move to a per-user lock or unique-per-day constraint if abuse appears.
            var usedToday = await _db.SpeakingSessions
                .CountAsync(s => s.UserId == userId && s.CreatedAt >= todayUtc, ct);
            if (usedToday >= dailyLimit)
                throw new QuotaExceededException("Daily speaking evaluation quota reached. Upgrade to Premium for unlimited evaluations.");
        }

        // Pronunciation (Azure PA) is client-aggregated but never client-scored: the band is always
        // recomputed here from the raw pronunciationScore, never trusted from the wire.
        var pronunciation = request.Pronunciation is { } pa
            ? pa with { Band = RoundToHalf(pa.PronunciationScore / 100 * 9), WordsPerMinute = SpeechRate(candidateTurns) }
            : null;
        if (pronunciation is not null)
            ValidatePronunciation(pronunciation);

        // Recorded before Gemini is paid, so a poll — or a retry — sees the attempt from here on.
        evaluation ??= _db.SpeakingEvaluations.Add(new SpeakingEvaluation { SpeakingEvaluationId = sessionId, UserId = userId }).Entity;
        evaluation.Status = SpeakingEvaluationStatus.Processing;
        evaluation.StartedAt = DateTime.UtcNow;
        evaluation.Error = null;
        await _db.SaveChangesAsync(ct);

        try
        {
            return await ScoreAndSaveAsync(userId, request, prompt, pronunciation, clips, evaluation);
        }
        catch (Exception ex)
        {
            // The page learns about this from its poll, the request may be long gone. Whatever failed
            // can still sit in the change tracker (a session that would not save), so the failure is
            // written on a clean slate — best effort: if even that fails, the poll reports the attempt
            // failed once it is StaleAfter old.
            _db.ChangeTracker.Clear();
            evaluation.Status = SpeakingEvaluationStatus.Failed;
            evaluation.Error = ex is TimeoutException
                ? "Scoring took longer than expected. Please try again."
                : "Scoring failed. Please try again.";
            _db.SpeakingEvaluations.Update(evaluation);
            try
            {
                await _db.SaveChangesAsync(CancellationToken.None);
            }
            catch
            {
                // see above
            }
            throw;
        }
    }

    /// <summary>The paid part of an evaluation: Gemini, then the session, then the recordings. Runs on
    /// CancellationToken.None throughout — the browser closing or dropping the request must not
    /// cancel a call that is being paid for; the poll, or the History page, picks the result up.</summary>
    private async Task<SpeakingSessionDto> ScoreAndSaveAsync(Guid userId, SpeakingEvaluateRequest request,
        SpeakingPrompt prompt, PronunciationResult? pronunciation, List<DecodedClip> clips, SpeakingEvaluation evaluation)
    {
        // No temperature: Gemini 3 models are tuned for their default, and lowering it risks looping
        // and weaker reasoning (Google's 3.8 Flash migration guide says to strip it). Bands stay
        // steady through the rubric in SpeakingFeedbackPrompts and the server-side average below.
        var thinkingLevel = GeminiStructuredClient.ThinkingLevelSetting(_config["GeminiScoringThinkingLevel"]);
        Task<GeminiResult<SpeakingFeedback>> Score(IReadOnlyCollection<DecodedClip> recordings) =>
            _gemini.GenerateAsync<SpeakingFeedback>(SpeakingFeedbackPrompts.SystemPrompt,
                BuildUserParts(prompt, request.Part, request.Turns, pronunciation, recordings),
                SpeakingFeedbackPrompts.GeminiSchema, CancellationToken.None,
                thinkingLevel: thinkingLevel, timeout: GeminiStructuredClient.ScoringTimeout);

        GeminiResult<SpeakingFeedback> result;
        try
        {
            result = await Score(clips);
        }
        // A 400 is rejected before any generation, so it costs nothing — and when the request carried
        // audio, an encoding Gemini will not read is the likeliest cause. Retry once without it so the
        // candidate still gets feedback, scored from the recognizer text alone.
        catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.BadRequest && clips.Count > 0)
        {
            result = await Score([]);
        }

        // Overall band is the average of the three Gemini-assessed criteria plus, when present, the
        // Azure PA band, rounded to the nearest 0.5 — not whatever Gemini put in its own overallBand field.
        var bands = result.Value.Criteria.Select(c => c.Band);
        if (pronunciation is not null)
            bands = bands.Append(pronunciation.Band);
        var overallBand = RoundToHalf(bands.Average());
        var feedback = result.Value with { OverallBand = overallBand };

        var session = new SpeakingSession
        {
            SpeakingSessionId = evaluation.SpeakingEvaluationId,
            UserId = userId,
            SpeakingPromptId = prompt.SpeakingPromptId,
            Part = request.Part,
            Turns = JsonSerializer.Serialize(request.Turns, CamelCase),
            OverallBand = overallBand,
            Feedback = JsonSerializer.Serialize(feedback, CamelCase),
            Pronunciation = pronunciation is null ? null : JsonSerializer.Serialize(pronunciation, CamelCase),
            FeedbackVersion = CurrentFeedbackVersion,
            AiModel = result.Model,
            PromptTokens = result.PromptTokens,
            CompletionTokens = result.CompletionTokens,
        };

        _db.SpeakingSessions.Add(session);
        // One save for both, so a poll never sees "completed" without the session to show.
        evaluation.Status = SpeakingEvaluationStatus.Completed;
        await _db.SaveChangesAsync(CancellationToken.None);

        // Playback copies, stored only once the paid result is safe in the database: a storage outage
        // costs the candidate the replay button, never the feedback.
        if (clips.Count > 0 && _audio.IsConfigured)
        {
            var stored = new List<StoredAudioClip>();
            foreach (var clip in clips)
            {
                // Under its own prefix in the shared container, so a lifecycle rule can expire
                // recordings without touching anything else stored there.
                var blobName = $"speaking-audio/{userId}/{session.SpeakingSessionId}/answer-{clip.Answer}.{clip.Extension}";
                if (await _audio.TryUploadAsync(blobName, clip.BrowserType, clip.Data))
                    stored.Add(new StoredAudioClip(clip.Answer, blobName));
            }
            if (stored.Count > 0)
            {
                session.AudioClips = JsonSerializer.Serialize(stored, CamelCase);
                await _db.SaveChangesAsync(CancellationToken.None);
            }
        }

        return new SpeakingSessionDto(session.SpeakingSessionId, session.OverallBand, feedback);
    }

    public async Task<SpeakingEvaluationStatusDto> GetEvaluationStatusAsync(Guid userId, Guid id)
    {
        // A saved session is the final word — it also covers sessions scored before polling existed.
        var session = await _db.SpeakingSessions.AsNoTracking()
            .FirstOrDefaultAsync(s => s.SpeakingSessionId == id && s.UserId == userId);
        if (session is not null)
            return new SpeakingEvaluationStatusDto(SpeakingEvaluationStatus.Completed, session.CreatedAt, null);

        var evaluation = await _db.SpeakingEvaluations.AsNoTracking()
            .FirstOrDefaultAsync(e => e.SpeakingEvaluationId == id && e.UserId == userId)
            ?? throw new NotFoundException("Evaluation not found.");
        // An attempt that died mid-call never wrote "failed"; past StaleAfter, report it for it.
        if (evaluation.Status == SpeakingEvaluationStatus.Processing && !IsRunning(evaluation))
            return new SpeakingEvaluationStatusDto(SpeakingEvaluationStatus.Failed, evaluation.StartedAt,
                "Scoring did not finish. Please try again.");
        return new SpeakingEvaluationStatusDto(evaluation.Status, evaluation.StartedAt, evaluation.Error);
    }

    private static bool IsRunning(SpeakingEvaluation evaluation) =>
        evaluation.Status == SpeakingEvaluationStatus.Processing && DateTime.UtcNow - evaluation.StartedAt < StaleAfter;

    public async Task<List<SpeakingSessionHistoryItemDto>> GetHistoryAsync(Guid userId)
    {
        return await _db.SpeakingSessions
            .Include(s => s.SpeakingPrompt)
            .Where(s => s.UserId == userId)
            .OrderByDescending(s => s.CreatedAt)
            .Select(s => new SpeakingSessionHistoryItemDto(
                s.SpeakingSessionId, s.Part, s.SpeakingPrompt.Topic, s.OverallBand, s.CreatedAt, s.SpeakingPromptId))
            .ToListAsync();
    }

    public async Task<SpeakingSessionDetailDto> GetDetailAsync(Guid userId, Guid id)
    {
        var session = await _db.SpeakingSessions
            .Include(s => s.SpeakingPrompt)
            .FirstOrDefaultAsync(s => s.SpeakingSessionId == id && s.UserId == userId)
            ?? throw new NotFoundException("Speaking session not found.");

        var turns = JsonSerializer.Deserialize<List<SpeakingTurn>>(session.Turns, CamelCase)!;
        var feedback = JsonSerializer.Deserialize<SpeakingFeedback>(session.Feedback, CamelCase)!;
        var pronunciation = session.Pronunciation is null
            ? null
            : JsonSerializer.Deserialize<PronunciationResult>(session.Pronunciation, CamelCase);
        // Signed fresh on every read and short-lived, so a copied link stops working on its own.
        var audio = new List<SpeakingAudioLink>();
        foreach (var clip in session.AudioClips is null ? [] : JsonSerializer.Deserialize<List<StoredAudioClip>>(session.AudioClips, CamelCase)!)
        {
            if (await _audio.ReadUrlAsync(clip.BlobName, AudioLinkLifetime) is { } url)
                audio.Add(new SpeakingAudioLink(clip.Answer, url));
        }
        return new SpeakingSessionDetailDto(
            session.SpeakingSessionId, session.Part, session.SpeakingPrompt.Topic, session.SpeakingPrompt.QuestionText,
            turns, session.OverallBand, feedback, pronunciation, session.CreatedAt,
            audio is { Count: > 0 } ? audio : null);
    }

    private static decimal RoundToHalf(decimal value) => Math.Round(value * 2, MidpointRounding.AwayFromZero) / 2;

    /// <summary>Words per minute across every spoken candidate turn: total words over total
    /// speaking time, not an average of per-turn rates, which would let a three-word answer weigh
    /// as much as a two-minute one. Words come from the raw lexical text — the display text drops
    /// repetitions the candidate really spoke. Null when there is too little speech to mean anything.</summary>
    internal static decimal? SpeechRate(IEnumerable<SpeakingTurn> candidateTurns)
    {
        var spoken = candidateTurns.Where(t => t.DurationSeconds > 0 && !string.IsNullOrWhiteSpace(t.Lexical)).ToList();
        var seconds = spoken.Sum(t => t.DurationSeconds!.Value);
        if (seconds < MinSecondsForSpeechRate)
            return null;
        var words = spoken.Sum(t => PauseMarker.Replace(t.Lexical!, " ")
            .Split(' ', StringSplitOptions.RemoveEmptyEntries).Length);
        return Math.Round(words / seconds * 60);
    }

    private static void ValidatePronunciation(PronunciationResult pa)
    {
        var scores = new[] { pa.PronunciationScore, pa.AccuracyScore, pa.FluencyScore, pa.ProsodyScore, pa.CompletenessScore };
        // NRT isn't runtime-enforced through System.Text.Json — "words": null on the wire lands here as null.
        if (scores.Any(s => s < 0 || s > 100) || pa.Words is null || pa.Words.Count > 400)
            throw new ValidationException("Invalid pronunciation assessment data.");
    }

    /// <summary>Shared with ExaminerService: the combined-turns cap protects the paid Gemini call
    /// regardless of which endpoint is building the prompt from client-controlled turns.</summary>
    internal static void ValidateConversationCap(List<SpeakingTurn> turns)
    {
        // Lexical counts too: it is client-controlled and BuildUserParts renders it verbatim
        // into the same paid call, so leaving it out would let a caller smuggle in a second
        // unbounded transcript past a cap that only ever looked at Text.
        var conversationLength = turns.Sum(t => (t.Text?.Length ?? 0) + (t.Lexical?.Length ?? 0));
        if (conversationLength > MaxConversationLength)
            throw new ValidationException("Conversation exceeds the maximum length of 30,000 characters.");
    }

    /// <summary>Validates the recordings and decodes their base64 before Gemini is paid: one recording
    /// per existing answer, in a format the practice page records, within the time and size caps.</summary>
    private static List<DecodedClip> DecodeAudio(List<SpeakingAudioClip>? clips, int answerCount)
    {
        if (clips is not { Count: > 0 })
            return [];
        if (clips.Any(c => c.Seconds <= 0) || clips.Sum(c => c.Seconds) > MaxAudioSeconds)
            throw new ValidationException("Recordings must be under five minutes in total.");
        if (clips.Any(c => c.Answer < 1 || c.Answer > answerCount)
            || clips.Select(c => c.Answer).Distinct().Count() != clips.Count)
            throw new ValidationException("Each recording must belong to a different answer.");

        var decoded = new List<DecodedClip>();
        var totalBytes = 0;
        foreach (var clip in clips)
        {
            var browserType = (clip.MimeType ?? "").Split(';')[0].Trim().ToLowerInvariant();
            if (!AudioTypes.TryGetValue(browserType, out var type))
                throw new ValidationException("Unsupported recording format.");
            byte[] data;
            try
            {
                data = Convert.FromBase64String(clip.Data ?? "");
            }
            catch (FormatException)
            {
                throw new ValidationException("Invalid recording data.");
            }
            totalBytes += data.Length;
            if (data.Length == 0 || totalBytes > MaxAudioBytes)
                throw new ValidationException("Recordings are empty or too large.");
            decoded.Add(new DecodedClip(clip.Answer, browserType, type.GeminiType, type.Extension, data));
        }
        return decoded;
    }

    private static List<GeminiPart> BuildUserParts(SpeakingPrompt prompt, string part, List<SpeakingTurn> turns,
        PronunciationResult? pronunciation, IReadOnlyCollection<DecodedClip> recordings)
    {
        var parts = new List<GeminiPart>();
        var recordingByAnswer = recordings.ToDictionary(r => r.Answer);
        var sb = new StringBuilder();
        sb.AppendLine($"Part: {part}");
        sb.AppendLine($"Question: {prompt.QuestionText}");
        if (!string.IsNullOrWhiteSpace(prompt.Cuepoints))
            sb.AppendLine($"Cue points: {prompt.Cuepoints}");
        // Gemini cannot time pauses itself, and only some answers come with a recording, so this is
        // the measured hesitation/pacing signal for the Fluency and Coherence band. Stated explicitly
        // when absent so it scores blind knowingly.
        sb.AppendLine(pronunciation is null
            ? "Measured speech fluency: not available (no spoken audio was assessed for this session)."
            : $"Measured speech fluency (0-100, from pause length, pause placement and speech rate): {pronunciation.FluencyScore:F0}");
        sb.AppendLine(pronunciation?.WordsPerMinute is { } wpm
            ? $"Measured speech rate: {wpm:F0} words per minute (speaking time only, pauses included)"
            : "Measured speech rate: not available.");
        // Candidate answers are numbered 1..n in conversation order, and the feedback refers back to
        // them by number (answers[].answer) — so both renderings below carry the same numbers, and a
        // typed answer with no raw recognition still takes its place in the count.
        var numbered = new List<(SpeakingTurn Turn, int? Answer)>();
        var answerCount = 0;
        foreach (var turn in turns)
            numbered.Add((turn, IsExaminer(turn) ? (int?)null : ++answerCount));

        sb.AppendLine("Transcript (display text — punctuation and sentence breaks added by the recognizer):");
        foreach (var (turn, answer) in numbered)
        {
            sb.AppendLine(answer is null ? $"Examiner: {turn.Text}" : $"Candidate (answer {answer}): {turn.Text}");
            // The recording goes right after its own answer's line, under the same number, so Gemini
            // never has to guess which question a clip answers.
            if (answer is { } n && recordingByAnswer.TryGetValue(n, out var recording))
            {
                sb.AppendLine($"Recording of answer {n}:");
                parts.Add(GeminiPart.FromText(sb.ToString()));
                parts.Add(GeminiPart.Inline(recording.GeminiType, recording.Data));
                sb.Clear();
            }
        }

        // The same candidate speech, unpolished. Only spoken turns have it, so the block is
        // omitted entirely for a typed session rather than printed empty — an empty heading
        // reads to the model like the candidate said nothing.
        var rawAnswers = numbered.Where(n => n.Answer is not null && !string.IsNullOrWhiteSpace(n.Turn.Lexical)).ToList();
        if (rawAnswers.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Raw recognition of the same candidate answers (verbatim, lowercase, no punctuation; "
                + "[pause N.Ns] marks a silence of at least one second):");
            foreach (var (turn, answer) in rawAnswers)
                sb.AppendLine($"Candidate (answer {answer}): {turn.Lexical}");
        }
        if (sb.Length > 0)
            parts.Add(GeminiPart.FromText(sb.ToString()));
        return parts;
    }

    private static bool IsExaminer(SpeakingTurn turn) =>
        turn.Role.Equals("examiner", StringComparison.OrdinalIgnoreCase);
}
